web-app/Perfectride/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ride/', include('ride.urls')),
    url(r'^', include('ride.urls')),
]

web-app/ride/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'ride'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('register/', views.register, name = 'register'),
    path('login_user/', views.login_user, name = 'login_user'),
    path('logout_user/', views.logout_user, name = 'logout_user'),
    url(r'^create_order/$', views.create_order, name = 'create_order'),
    url(r'^update_profile/$', views.update_profile, name = 'update_profile'),
    url(r'^(?P<order_id>[0-9]+)/update_order/$', views.update_order, name= 'update_order'),
    url(r'^profile_detail/$',views.profile_detail, name = 'profile_detail'),
    url(r'^driversearch/$', views.driversearch, name = 'driversearch'),
    url(r'^(?P<order_id>[0-9]+)/detail/$', views.detail, name='detail'),
    url(r'^(?P<order_id>[0-9]+)/driverdetail/$', views.driverdetail, name='driverdetail'),
    url(r'^(?P<order_id>[0-9]+)/sharer_ask/$', views.sharer_ask, name='sharer_ask'),
    url(r'^sharersearch/$', views.sharersearch, name='sharersearch'),
    url(r'^(?P<order_id>[0-9]+)/driver_choose/$', views.driver_choose, name='driver_choose'),
    url(r'^(?P<order_id>[0-9]+)/complete/$', views.complete, name='complete'),

]

web-app/ride/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
import django.utils.timezone as timezone

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    phone = models.CharField(max_length=20, blank=True)
    is_driver = models.BooleanField(default=False,null=True)
    vehicle_type = models.CharField(max_length=20, blank=True, null=True)
    vehicle_license = models.CharField(max_length=20, blank=True, null=True)
    vehicle_max_passenger = models.IntegerField(blank=True, null=True, default=0)
    vehicle_special_info = models.CharField(max_length=150, blank=True, null=True)

    @receiver(post_save, sender=User)
    def created_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()


class OrderInfo(models.Model):
    created_time = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    owner_id = models.CharField(max_length=80, blank=True)
    sharer_id = models.CharField(max_length=80, blank=True, null=True)
    status = models.CharField(max_length=40)
    starting_address = models.CharField(max_length=150)
    destination_address = models.CharField(max_length=150)
    new_starting_address = models.CharField(max_length=150,null=True)
    new_destination_address = models.CharField(max_length=150,null=True)
    share_permission = models.BooleanField(null=True)
    required_arrival_date = models.DateField(default=timezone.now)
    required_arrival_time = models.TimeField(default=timezone.now)
    preferred_vehicle_type = models.CharField(max_length=30, blank=True, null=True)
    driver_id = models.CharField(max_length=80, blank=True, null=True)
    special_requests = models.CharField(max_length=150, blank=True, null=True)
    number_of_passengers = models.IntegerField(default=1)
    driver_status = models.CharField(max_length=30,default='NONE')
    number_of_ownerpassengers = models.IntegerField(default=1)
    dirvers_car_capacity = models.IntegerField(null=True)
    remain_space = models.IntegerField(null=True)
    canceled = models.BooleanField(null=True)

    def __str(self):
        return self.created_time

web-app/ride/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile, OrderInfo




class  RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['phone', 'is_driver', 'vehicle_type', 'vehicle_license', 'vehicle_special_info', \
                  'vehicle_max_passenger']


class OrderForm(forms.ModelForm):

    class Meta:
        model = OrderInfo
        fields = ['starting_address', 'destination_address', 'share_permission', 'required_arrival_date', \
                  'required_arrival_time', 'preferred_vehicle_type', 'special_requests', 'number_of_ownerpassengers']


class SharerForm(forms.ModelForm):
    number_of_passengers = forms.IntegerField(widget=forms.NumberInput)

    class Meta:
        model = OrderInfo
        fields = ['number_of_passengers']

class SearchFormDriver(forms.ModelForm):

    class Meta:
        model = OrderInfo
        fields = ['starting_address', 'destination_address' , 'required_arrival_date', 'preferred_vehicle_type']


class SearchFormSharer(forms.ModelForm):

    class Meta:
        model = OrderInfo
        fields = ['starting_address', 'destination_address', 'required_arrival_date', 'number_of_passengers']

class OwnerupdateForm(forms.ModelForm):

    class Meta:
        model = OrderInfo
        fields = ['new_starting_address', 'new_destination_address', 'share_permission', 'required_arrival_date', \
                  'required_arrival_time', 'preferred_vehicle_type', 'special_requests', 'number_of_passengers', 'canceled']

class SharerupdatedForm(forms.ModelForm):

    class Meta:
        model = OrderInfo
        fields = ['number_of_passengers', 'canceled']

web-app/ride/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django import forms
from .models import *
from django.db.models import Q
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from .forms import ProfileForm, OrderForm, RegisterForm, SharerForm, SearchFormDriver, SearchFormSharer, OwnerupdateForm,  SharerupdatedForm
from .models import Profile, OrderInfo
from django.http import JsonResponse
from django.contrib.auth.models import Permission, User
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.conf import settings
# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'ride/login.html')
    else:
        created_orders = OrderInfo.objects.filter(owner_id=request.user.username)
        shared_orders = OrderInfo.objects.filter(sharer_id=request.user.username)
        drived_orders = OrderInfo.objects.filter(driver_id=request.user.username)
        return render(request, 'ride/index.html', {'created_orders': created_orders, 'shared_orders': shared_orders,
                                                   'drived_orders': drived_orders})


def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                created_orders = OrderInfo.objects.filter(owner_id=request.user.username)
                shared_orders = OrderInfo.objects.filter(sharer_id=request.user.username)
                drived_orders = OrderInfo.objects.filter(driver_id=request.user.username)
                return render(request, 'ride/index.html',
                              {'created_orders': created_orders, 'shared_orders': shared_orders,
                               'drived_orders': drived_orders})
    context = {
        "form": form,
    }
    return render(request, 'ride/register.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                created_orders = OrderInfo.objects.filter(owner_id=request.user.username)
                shared_orders = OrderInfo.objects.filter(sharer_id=request.user.username)
                drived_orders = OrderInfo.objects.filter(driver_id=request.user.username)
                return render(request, 'ride/index.html',
                              {'created_orders': created_orders, 'shared_orders': shared_orders,
                               'drived_orders': drived_orders})

            else:
                return render(request, 'ride/login.html', {'error_message': 'Invalid login'})
    return render(request, 'ride/login.html')


def logout_user(request):
    logout(request)
    form = ProfileForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'ride/login.html', context)


def detail(request, order_id):
    if not request.user.is_authenticated:
        return render(request, 'ride/login.html')
    else:
        user = request.user
        order = get_object_or_404(OrderInfo, pk=order_id)
        return render(request, 'ride/detail.html', {'order': order, 'user': user})


def create_order(request):
    if not request.user.is_authenticated:
        return render(request, 'ride/login.html')
    else:
        form = OrderForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            order = form.save(commit=False)
            order.owner_id = request.user.username
            order.special_requests = request.POST['special_requests']
            if request.POST['number_of_ownerpassengers']:
                order.number_of_passengers = request.POST['number_of_ownerpassengers']
                order.number_of_ownerpassengers = request.POST['number_of_ownerpassengers']
            else:
                order.number_of_passengers = 1
                order.number_of_ownerpassengers = 1
            order.destination_address = request.POST['destination_address']
            order.required_arrival_date = request.POST['required_arrival_date']
            order.required_arrival_time = request.POST['required_arrival_time']

            order.preferred_vehicle_type = request.POST['preferred_vehicle_type']
            if request.POST['share_permission'] == '2':
                order.share_permission = True
                order.status = 'waiting'
            else:
                order.share_permission = False
                order.status = 'waiting'
            order.number_of_ownerpassengers = request.POST['number_of_ownerpassengers']
            order.save()
            created_orders = OrderInfo.objects.filter(owner_id=request.user.username)
            shared_orders = OrderInfo.objects.filter(sharer_id=request.user.username)
            drived_orders = OrderInfo.objects.filter(driver_id=request.user.username)
            return render(request, 'ride/index.html',
                          {'created_orders': created_orders, 'shared_orders': shared_orders,
                           'drived_orders': drived_orders})

    context = {
        "form": form,
    }

    return render(request, 'ride/create_order.html', context)


def update_profile(request):
    if not request.user.is_authenticated:
        return render(request, 'ride/login.html')
    else:
        form = ProfileForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            user = request.user
            user.profile.phone = request.POST['phone']
            if request.POST['is_driver'] == '2':
                user.profile.is_driver = True
            else:
                user.profile.is_driver = False
            if request.POST['vehicle_max_passenger']:
                user.profile.vehicle_max_passenger = request.POST['vehicle_max_passenger']
            user.profile.vehicle_license = request.POST['vehicle_license']
            user.profile.vehicle_type = request.POST['vehicle_type']
            user.profile.vehicle_special_info = request.POST['vehicle_special_info']
            user.save()
            return render(request,'ride/profile_detail.html',{'user':user})

    context = {
        'form':form,
    }

    return render(request, 'ride/update_profile.html', context)


def profile_detail(request):
    if not request.user.is_authenticated:
        return render(request, 'ride/login.html')
    else:
        user = request.user
        return render(request, 'ride/profile_detail.html', {'user':user})

def sharersearch(request):
    if not request.user.is_authenticated:
        return render(request, 'ride/login.html')
    else:
        form = SearchFormSharer(request.POST or None, request.FILES or None)
        if form.is_valid():
            orders = OrderInfo.objects.filter(starting_address=request.POST['starting_address'])
            orders = orders.filter(destination_address=request.POST['destination_address'])
            orders = orders.filter(required_arrival_date=request.POST['required_arrival_date'])
            orders = orders.filter(status='waitingsharer')
            number = int(request.POST['number_of_passengers'])
            for num in range(0,number):
                orders = orders.exclude(remain_space=num)
            return render(request, 'ride/join_order.html', {'shareorders':orders})

    context = {
        'form':form,
    }
    return render(request, 'ride/sharersearch.html', context)

def sharer_ask(request,order_id):
    if not request.user.is_authenticated:
        return render(request, 'ride/login.html')
    else:
        form = SharerForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            order = OrderInfo.objects.get(pk=order_id)
            valid_number = order.dirvers_car_capacity - order.number_of_passengers
            if int(request.POST['number_of_passengers']) <= valid_number:
                order.number_of_passengers += int(request.POST['number_of_passengers'])
                order.sharer_id = request.user.username
                order.remain_space = order.dirvers_car_capacity - order.number_of_passengers
                order.status = 'sharerjoined'
                order.save()
                email = request.user.email
                send_mail('Order joined', 'At ubber, we use the capacity of car to filter your search result.\n A order must be confirmed by driver first\n You will not receive a confrimed email again, however you joined this order successfully now!', settings.DEFAULT_FROM_EMAIL,
                          [email], fail_silently=False)
                created_orders = OrderInfo.objects.filter(owner_id=request.user.username)
                shared_orders = OrderInfo.objects.filter(sharer_id=request.user.username)
                drived_orders = OrderInfo.objects.filter(driver_id=request.user.username)
                return render(request, 'ride/index.html',
                             {'created_orders': created_orders, 'shared_orders': shared_orders,
                              'drived_orders': drived_orders})
            else:
                form = SearchFormSharer(request.POST or None, request.FILES or None)
                if form.is_valid():
                    orders = OrderInfo.objects.filter(starting_address=request.POST['starting_address'])
                    orders = orders.filter(destination_address=request.POST['destination_address'])

web-app/ride/templates/ride/accept_orders.html
{% extends 'ride/base.html' %}

{% load static %}

{% block title %}
    Your orders
{% endblock %}

{% block body %}
    <div>
    <h1>choose an order to drive</h1>
    <p>If you accept an order with a too large number of passengers, this acceptence will not be successful. </p>
    <table border="3",cellpadding="10" cellspacing="20">>
        <thead>
        <tr>
            <th>rider</th>
            <th>starting_address</th>
            <th>destination</th>
            <th>arrival date</th>
            <th>arrival time</th>
            <th>number of passengers</th>
            <th>preferred vehicle type</th>
            <th>driver</th>
            <th>sharer</th><!--check if need to add sharer's destination-->
            <th>specail_requests</th>
            <th>status</th>
            <th>click to accept</th>

        </tr>
        </thead>
        <tbody>

            {% for order in waitingorders %}
            <tr>
                <th>{{ order.owner_id }}</th>
                <th>{{ order.starting_address }}</th>
                <th>{{ order.destination_address }}</th>
                <th>{{ order.required_arrival_date }}</th>
                <th>{{ order.required_arrival_time }}</th>
                <th>{{ order.number_of_passengers }}</th>
                <th>{{ order.preferred_vehicle_type }}</th>
                <th>{{ order.driver_id }}</th>
                <th>{{ order.sharer_id }}</th>
                <th>{{ order.special_requests }}</th>
                <th>{{ order.status }}</th>
                <th>
                    <a href="{% url 'ride:driver_choose' order.id %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Accept
                    </button>
                    </a >
                </th>
            </tr>
            {% endfor %}


        </tbody>
    </table>
    </div>
       

{% endblock %}

web-app/ride/templates/ride/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Ubber{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'ride/style.css' %}"/>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'ride:index' %}">Ubber</a >
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block order_active %}{% endblock %}"><a href="{% url 'ride:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; order</a ></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'ride:create_order' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; created order
                    </a >
                </li>
                <li>
                    <a href="{% url 'ride:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a >
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

web-app/ride/templates/ride/detail.html
{% extends 'ride/base.html' %}

{% load static %}

{% block title %}
    Your orders
{% endblock %}

{% block body %}
    <h1>Your order's detail</h1>
    <table border="3",cellpadding="10" cellspacing="20">>
        <thead>
        <tr>
            <th>rider</th>
            <th>starting_address</th>
            <th>destination</th>
            <th>arrival date</th>
            <th>arrival time</th>
            <th>number of passengers</th>
            <th>dirvers'car capacity</th>
            <th>preferred vehicle type</th>
            <th>driver</th>
            <th>sharer</th><!--check if need to add sharer's destination-->
            <th>specail_requests</th>
            <th>status</th>
            <th>edit</th>
           


        </tr>
        </thead>
        <tbody>
        {% if order %}
            <tr>
                <th>{{ order.owner_id }}</th>
                <th>{{ order.starting_address }}</th>
                <th>{{ order.destination_address }}</th>
                <th>{{ order.required_arrival_date }}</th>
                <th>{{ order.required_arrival_time }}</th>
                <th>{{ order.number_of_passengers }}</th>
                <th>{{ order.dirvers_car_capacity}}</th>
                <th>{{ order.preferred_vehicle_type }}</th>
                <th>{{ order.driver_id }}</th>
                <th>{{ order.sharer_id }}</th>
                <th>{{ order.special_requests }}</th>
                <th>{{ order.status }}</th>
                <th>
                    <a href="{% url 'ride:update_order' order.id %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; edit
                    </button>
                    </a >
                </th>

            </tr>
        {% endif %}
            
        </tbody>
    </table>

{% endblock %}

web-app/ride/templates/ride/driverdetail.html
{% extends 'ride/base.html' %}

{% load static %}

{% block title %}
    Your orders
{% endblock %}

{% block body %}
    <h1>Your order's detail</h1>
    <table border="3",cellpadding="10" cellspacing="20">>
        <thead>
        <tr>
            <th>rider</th>
            <th>starting_address</th>
            <th>destination</th>
            <th>arrival date</th>
            <th>arrival time</th>
            <th>number of passengers</th>
            <th>dirvers'car capacity</th>
            <th>preferred vehicle type</th>
            <th>driver</th>
            <th>sharer</th><!--check if need to add sharer's destination-->
            <th>specail_requests</th>
            <th>status</th>
            <th>complete</th>



        </tr>
        </thead>
        <tbody>
        {% if order %}
            <tr>
                <th>{{ order.owner_id }}</th>
                <th>{{ order.starting_address }}</th>
                <th>{{ order.destination_address }}</th>
                <th>{{ order.required_arrival_date }}</th>
                <th>{{ order.required_arrival_time }}</th>
                <th>{{ order.number_of_passengers }}</th>
                <th>{{ order.dirvers_car_capacity}}</th>
                <th>{{ order.preferred_vehicle_type }}</th>
                <th>{{ order.driver_id }}</th>
                <th>{{ order.sharer_id }}</th>
                <th>{{ order.special_requests }}</th>
                <th>{{ order.status }}</th>
                <th>
                    <a href="{% url 'ride:complete' order.id %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; complete
                    </button>
                    </a >
                </th>

            </tr>
        {% endif %}

        </tbody>
    </table>

{% endblock %}

web-app/ride/templates/ride/index.html
{% extends 'ride/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="OrderInfo-container container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Orders</h3>
        </div>
        <div class="col-sm-12">
        <h4><a href="{% url 'ride:profile_detail' %}">{{ user.username}}'s Profile</a> </h4>
        </div>

        <div class="col-sm-12">
            <h4>orders you created</h4>
        {% if created_orders %}

            {% for order in created_orders %}
            <li><a href="{% url 'ride:detail' order.id %}">{{ order.created_time }}</a> </li>

                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% endif %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'ride:create_order' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Create an order
                    </button>
                </a >
            </div>
        </div>

        <div class="col-sm-12">
            <h4>orders you shared</h4>
        {% if shared_orders %}

            {% for order in shared_orders %}
            <li><a href="{% url 'ride:detail' order.id %}">{{ order.created_time }}</a> </li>

                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% endif %}

            <div class="col-sm-12">
                <br>
                <a href="{% url 'ride:sharersearch' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Join an order
                    </button>
                </a >
            </div>
        </div>

        <div class="col-sm-12">
            <h4>orders you accepted</h4>
        {% if drived_orders %}

            {% for order in drived_orders %}
            <li><a href="{% url 'ride:driverdetail' order.id %}">{{ order.created_time }}</a> </li>

                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% endif %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'ride:driversearch' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Accept an order
                    </button>
                </a >
            </div>
            <a href="{% url 'ride:update_profile' %}">If you are not a driver, click here</a>
        </div>

    </div>

</div>
{% endblock %}

web-app/ride/templates/ride/join_order.html
{% extends 'ride/base.html' %}

{% load static %}

{% block title %}
    Your orders
{% endblock %}

{% block body %}
    <h1 class="col-sm-12">choose an order to join</h1>
    <table border="3",cellpadding="10" cellspacing="20" class="col-sm-12">
        <thead>
        <tr>
            <th>rider</th>
            <th>destination</th>
            <th>arrival date</th>
            <th>arrival time</th>
            <th>number of passengers</th>
            <th>preferred vehicle type</th>
            <th>driver</th>
            <th>sharer</th><!--check if need to add sharer's destination-->
            <th>specail_requests</th>
            <th>status</th>
            <th>car's capacity</th>
            <th>click to choose</th>
        </tr>
        </thead>
        <tbody>

            {% for order in shareorders %}
            <tr>
                <th>{{ order.owner_id }}</th>
                <th>{{ order.destination_address }}</th>
                <th>{{ order.required_arrival_date }}</th>
                <th>{{ order.required_arrival_time }}</th>
                <th>{{ order.number_of_passengers }}</th>
                <th>{{ order.preferred_vehicle_type }}</th>
                <th>{{ order.driver_id }}</th>
                <th>{{ order.sharer_id }}</th>
                <th>{{ order.special_requests }}</th>
                <th>{{ order.status }}</th>
                <th>{{ order.dirvers_car_capacity }}</th>
                <th>
                    <a href="{% url 'ride:sharer_ask' order.id %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Join
                    </button>
                    </a >
                </th>
            </tr>
            {% endfor %}
        

        </tbody>
    </table>
<div class="col-sm-12">
    <body>
    <h3>mention:</h3>
    you couldn't join an order if the total number of passengers exceeds the capacity of the car
    </body>
</div>

{% endblock %}

web-app/ride/templates/ride/login.html
{% extends 'ride/base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p >
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'ride:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href=" {% url 'ride:register' %}">Click here</a > to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

web-app/ride/templates/ride/register.html
{% extends 'ride/base.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p >
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'ride/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                     Already have an account? <a href="{% url 'ride:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}